### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by coderholic** [betastreet/exchange-pubsub#13]
Is there any way to disable logging, other than doing something like this?

```
pubsub.setOptions({
    log: {
        trace: () ->
        warn: () ->
        error: () ->
        log: () ->
    }
```

If I pass in `log: false` then the code sets log back to the default of console

**Comment by 6utt3rfly** [comment]
Is PR #14 okay for you?

**Comment by 6utt3rfly** [comment]
Release 1.2.11
